# Generated by Django 5.2.3 on 2025-07-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.CharField(max_length=500),
        ),
    ]
