# Generated by Django 5.2.3 on 2025-07-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.TextField(),
        ),
    ]
