# Generated by Django 5.2.3 on 2025-07-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
