# Generated by Django 5.2.3 on 2025-07-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_quiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
