# Generated by Django 5.2.3 on 2025-07-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_student_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
    ]
